// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ShopAxis.Agent.Migrations
{
    [DbContext(typeof(ShopAxisDbContext))]
    partial class ShopAxisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wireless Headphones",
                            OrderId = "ORD-00482917",
                            Price = 89.99m,
                            Qty = 1,
                            Sku = "SKU-1042"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Standing Desk Mat",
                            OrderId = "ORD-00391045",
                            Price = 45.00m,
                            Qty = 1,
                            Sku = "SKU-2087"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mechanical Keyboard",
                            OrderId = "ORD-00512334",
                            Price = 129.99m,
                            Qty = 1,
                            Sku = "SKU-3301"
                        },
                        new
                        {
                            Id = 4,
                            Name = "USB-C Hub",
                            OrderId = "ORD-00734521",
                            Price = 35.00m,
                            Qty = 2,
                            Sku = "SKU-5521"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Laptop Stand",
                            OrderId = "ORD-00734521",
                            Price = 59.99m,
                            Qty = 1,
                            Sku = "SKU-5522"
                        });
                });

            modelBuilder.Entity("OrderRecord", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EstimatedDelivery")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "ORD-00482917",
                            Carrier = "FedEx",
                            CustomerEmail = "sarah.chen@example.com",
                            EstimatedDelivery = new DateOnly(2026, 5, 2),
                            Status = "shipped",
                            TrackingNumber = "794644792798"
                        },
                        new
                        {
                            OrderId = "ORD-00391045",
                            Carrier = "UPS",
                            CustomerEmail = "james.park@example.com",
                            DeliveryDate = new DateOnly(2026, 3, 25),
                            EstimatedDelivery = new DateOnly(2026, 3, 25),
                            Status = "delivered",
                            TrackingNumber = "1Z999AA10123456784"
                        },
                        new
                        {
                            OrderId = "ORD-00512334",
                            Carrier = "DHL",
                            CustomerEmail = "angry@example.com",
                            EstimatedDelivery = new DateOnly(2026, 4, 30),
                            Status = "out_for_delivery",
                            TrackingNumber = "1234567890"
                        },
                        new
                        {
                            OrderId = "ORD-00734521",
                            Carrier = "UPS",
                            CustomerEmail = "lisa.wang@example.com",
                            DeliveryDate = new DateOnly(2026, 4, 9),
                            EstimatedDelivery = new DateOnly(2026, 4, 9),
                            Status = "delivered",
                            TrackingNumber = "1Z999AA10987654321"
                        });
                });

            modelBuilder.Entity("ReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RmaNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RmaNumber");

                    b.ToTable("ReturnItems");
                });

            modelBuilder.Entity("ReturnRecord", b =>
                {
                    b.Property<string>("RmaNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ExpectedCompletion")
                        .HasColumnType("date");

                    b.Property<string>("LabelUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RefundStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RmaNumber");

                    b.HasIndex("OrderId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("OrderRecord", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ReturnItem", b =>
                {
                    b.HasOne("ReturnRecord", "Return")
                        .WithMany("ReturnItems")
                        .HasForeignKey("RmaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("ReturnRecord", b =>
                {
                    b.HasOne("OrderRecord", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReturnRecord", b =>
                {
                    b.Navigation("ReturnItems");
                });
#pragma warning restore 612, 618
        }
    }
}
